# Generated by Django 2.2.4 on 2019-09-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Navnet på stream eventet.', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Stedet det streames ifra.', max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, help_text='Når arrangmentet starter', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='Når arrangmentet stopper', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LowerThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Navnet til den som er på tv.', max_length=255)),
                ('title', models.CharField(help_text='Tittelen på talken', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowerthirds', to='graphics.Event')),
            ],
        ),
    ]
