# Generated by Django 2.2.4 on 2019-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerthird',
            name='title',
            field=models.CharField(blank=True, help_text='Tittelen på talken', max_length=255, null=True),
        ),
    ]
