# Generated by Django 2.2.4 on 2020-01-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_auto_20191023_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='filnavn på template for grafikk.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lowerthird',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='graphics.Template'),
            preserve_default=False,
        ),
    ]
